// modules
const randomSelector = require("./randomSelector");

// list of major cities in Nigeria
const cities =  [
    "Aba",
    "Abakaliki",
    "Abeokuta",
    "Abraka",
    "Abuja",
    "Ado-Ekiti",
    "Agege",
    "Akure",
    "Alimosho",
    "Anambra",
    "Apapa",
    "Benin City",
    "Birnin Kebbi",
    "Burutu",
    "Bwari",
    "Calabar",
    "Damaturu",
    "Egbeda",
    "Ekpoma",
    "Enugu",
    "Forum",
    "Funtua",
    "Ibadan",
    "Ido",
    "Ifako",
    "Igando",
    "Ikeja",
    "Ikorodu",
    "Ile-Ife",
    "Ilesa",
    "Ilorin",
    "Isolo",
    "Jalingo",
    "Jos",
    "Katsina",
    "Kaduna",
    "Kano",
    "Kebbi",
    "Lagos",
    "Lokoja",
    "Makurdi",
    "Maryland",
    "Minna",
    "Mowe",
    "Mushin",
    "Nsukka",
    "Obudu",
    "Ondo",
    "Ogbomosho",
    "Osogbo",
    "Ota",
    "Owerri",
    "Port Harcourt",
    "Suleja",
    "Suru-Lere",
    "Ughelli",
    "Uyo",
    "Warri",
    "Yola",
    "Zaria"
  ]

const getLocation = () => randomSelector(cities);

module.exports = getLocation;
